# 50-State Programmatic SEO Page Generator
$targetFolder = Join-Path $home "OneDrive\Desktop\nonprofit-pages"
if (!(Test-Path $targetFolder)) { New-Item -ItemType Directory -Path $targetFolder }

$states = @(
    @{name="Alabama"; fee="100"; board="3"; agency="Alabama Secretary of State"; file="alabama.html"},
    @{name="Alaska"; fee="25"; board="3"; agency="Alaska Department of Commerce"; file="alaska.html"},
    @{name="Arizona"; fee="40"; board="3"; agency="Arizona Corporation Commission"; file="arizona.html"},
    @{name="Arkansas"; fee="50"; board="3"; agency="Arkansas Secretary of State"; file="arkansas.html"},
    @{name="California"; fee="30"; board="1"; agency="California Secretary of State"; file="california.html"},
    @{name="Colorado"; fee="50"; board="3"; agency="Colorado Secretary of State"; file="colorado.html"},
    @{name="Connecticut"; fee="50"; board="3"; agency="Connecticut Secretary of the State"; file="connecticut.html"},
    @{name="Delaware"; fee="89"; board="1"; agency="Delaware Division of Corporations"; file="delaware.html"},
    @{name="Florida"; fee="70"; board="3"; agency="Florida Division of Corporations"; file="florida.html"},
    @{name="Georgia"; fee="100"; board="3"; agency="Georgia Secretary of State"; file="georgia.html"},
    @{name="Hawaii"; fee="25"; board="3"; agency="Hawaii Department of Commerce"; file="hawaii.html"},
    @{name="Idaho"; fee="30"; board="3"; agency="Idaho Secretary of State"; file="idaho.html"},
    @{name="Illinois"; fee="50"; board="3"; agency="Illinois Secretary of State"; file="illinois.html"},
    @{name="Indiana"; fee="30"; board="3"; agency="Indiana Secretary of State"; file="indiana.html"},
    @{name="Iowa"; fee="20"; board="3"; agency="Iowa Secretary of State"; file="iowa.html"},
    @{name="Kansas"; fee="20"; board="3"; agency="Kansas Secretary of State"; file="kansas.html"},
    @{name="Kentucky"; fee="8"; board="3"; agency="Kentucky Secretary of State"; file="kentucky.html"},
    @{name="Louisiana"; fee="75"; board="3"; agency="Louisiana Secretary of State"; file="louisiana.html"},
    @{name="Maine"; fee="40"; board="3"; agency="Maine Secretary of State"; file="maine.html"},
    @{name="Maryland"; fee="170"; board="3"; agency="Maryland Department of Assessments and Taxation"; file="maryland.html"},
    @{name="Massachusetts"; fee="70"; board="3"; agency="Massachusetts Corporations Division"; file="massachusetts.html"},
    @{name="Michigan"; fee="20"; board="3"; agency="Michigan Department of Licensing and Regulatory Affairs"; file="michigan.html"},
    @{name="Minnesota"; fee="70"; board="3"; agency="Minnesota Secretary of State"; file="minnesota.html"},
    @{name="Mississippi"; fee="50"; board="3"; agency="Mississippi Secretary of State"; file="mississippi.html"},
    @{name="Missouri"; fee="25"; board="3"; agency="Missouri Secretary of State"; file="missouri.html"},
    @{name="Montana"; fee="20"; board="3"; agency="Montana Secretary of State"; file="montana.html"},
    @{name="Nebraska"; fee="25"; board="3"; agency="Nebraska Secretary of State"; file="nebraska.html"},
    @{name="Nevada"; fee="50"; board="3"; agency="Nevada Secretary of State"; file="nevada.html"},
    @{name="New-Hampshire"; fee="25"; board="5"; agency="New Hampshire Department of State"; file="new-hampshire.html"},
    @{name="New-Jersey"; fee="75"; board="3"; agency="New Jersey Division of Revenue"; file="new-jersey.html"},
    @{name="New-Mexico"; fee="25"; board="3"; agency="New Mexico Secretary of State"; file="new-mexico.html"},
    @{name="New-York"; fee="75"; board="3"; agency="New York Department of State"; file="new-york.html"},
    @{name="North-Carolina"; fee="60"; board="1"; agency="North Carolina Secretary of State"; file="north-carolina.html"},
    @{name="North-Dakota"; fee="40"; board="3"; agency="North Dakota Secretary of State"; file="north-dakota.html"},
    @{name="Ohio"; fee="99"; board="3"; agency="Ohio Secretary of State"; file="ohio.html"},
    @{name="Oklahoma"; fee="25"; board="3"; agency="Oklahoma Secretary of State"; file="oklahoma.html"},
    @{name="Oregon"; fee="50"; board="3"; agency="Oregon Secretary of State"; file="oregon.html"},
    @{name="Pennsylvania"; fee="125"; board="1"; agency="Pennsylvania Department of State"; file="pennsylvania.html"},
    @{name="Rhode-Island"; fee="85"; board="3"; agency="Rhode Island Department of State"; file="rhode-island.html"},
    @{name="South-Carolina"; fee="25"; board="3"; agency="South Carolina Secretary of State"; file="south-carolina.html"},
    @{name="South-Dakota"; fee="30"; board="3"; agency="South Dakota Secretary of State"; file="south-dakota.html"},
    @{name="Tennessee"; fee="100"; board="3"; agency="Tennessee Secretary of State"; file="tennessee.html"},
    @{name="Texas"; fee="25"; board="3"; agency="Texas Secretary of State"; file="texas.html"},
    @{name="Utah"; fee="30"; board="3"; agency="Utah Division of Corporations"; file="utah.html"},
    @{name="Vermont"; fee="125"; board="3"; agency="Vermont Secretary of State"; file="vermont.html"},
    @{name="Virginia"; fee="75"; board="3"; agency="Virginia State Corporation Commission"; file="virginia.html"},
    @{name="Washington"; fee="60"; board="1"; agency="Washington Secretary of State"; file="washington.html"},
    @{name="West-Virginia"; fee="25"; board="3"; agency="West Virginia Secretary of State"; file="west-virginia.html"},
    @{name="Wisconsin"; fee="35"; board="3"; agency="Wisconsin Department of Financial Institutions"; file="wisconsin.html"},
    @{name="Wyoming"; fee="50"; board="3"; agency="Wyoming Secretary of State"; file="wyoming.html"}
)

$templateLines = @(
'<!DOCTYPE html>',
'<html>',
'<head>',
'    <meta charset="UTF-8">',
'    <title>How to Start a Nonprofit in {{STATE}} - Checklist and Quiz</title>',
'</head>',
'<body style="background-color: #f4f6f9; display: flex; flex-direction: column; align-items: center; padding: 40px 20px; margin: 0; font-family: -apple-system, BlinkMacSystemFont, \x27Segoe UI\x27, Roboto, sans-serif;">',
'',
'  <div style="max-width: 450px; width: 90%; background: #ffffff; padding: 25px; border-radius: 12px; box-shadow: 0 4px 15px rgba(0,0,0,0.05); margin-bottom: 20px;">',
'    <h1 style="color: #1e293b; font-size: 22px; margin-top: 0; text-align: center;">Starting a Nonprofit in {{STATE}}</h1>',
'    <p style="color: #475569; font-size: 14px; line-height: 1.6;">If you are launching a 501(c)(3) organization in {{STATE}}, you must file your incorporation paperwork directly with the <b>{{AGENCY}}</b>. The state filing fee is <b>${{FEE}}</b>, and you are required to have a minimum of <b>{{BOARD}} board members</b> to stay compliant.</p>',
'  </div>',
'',
'  <div id="quiz-box" style="max-width: 450px; width: 90%; padding: 30px; background-color: #ffffff; border-radius: 12px; box-shadow: 0 4px 15px rgba(0,0,0,0.05); text-align: center;">',
'    <div id="quiz-content">',
'      <h2 style="color: #1e293b; margin-top: 0;">Is Your {{STATE}} Idea Ready?</h2>',
'      <p style="color: #64748b; font-size: 15px; margin-bottom: 25px;">Take our 60-second compliance readiness quiz to see if you\x27re ready to submit to the state.</p>',
'      ',
'      <div style="background-color: #f8fafc; padding: 20px; border-radius: 8px; border: 1px solid #e2e8f0; margin-bottom: 25px;">',
'        <p id="question-text" style="color: #334155; font-size: 16px; font-weight: 600; margin: 0; line-height: 1.5;">Question 1: Do you have at least {{BOARD}} board members ready to join?</p>',
'      </div>',
'',
'      <button onclick="answerQuestion(1)" style="background-color: #2563eb; color: white; border: none; padding: 12px 28px; font-size: 15px; font-weight: bold; border-radius: 6px; cursor: pointer; margin: 5px; width: 140px;">Yes</button>',
'      <button onclick="answerQuestion(0)" style="background-color: #e2e8f0; color: #475569; border: none; padding: 12px 28px; font-size: 15px; font-weight: bold; border-radius: 6px; cursor: pointer; margin: 5px; width: 140px;">No / Unsure</button>',
'    </div>',
'  </div>',
'',
'  <script>',
'    let currentScore = 0;',
'    let currentQuestion = 1;',
'    const GOOGLE_SCRIPT_URL = "https://script.google.com/macros/s/AKfycbzlPUlvQ73j_TIfsjAAVMK4ELUkkZFDs64o54kyLx6701uktkakkPBDiLpx8-RGxMZ2/exec";',
'',
'    const questions = [',
'      "Do you have at least {{BOARD}} board members ready to join?",',
'      "Have you drafted your nonprofit\x27s official Bylaws yet?",',
'      "Do you know your state\x27s exact corporate filing fee?",',
'      "Do you have a clear, 1-sentence charitable mission statement?",',
'      "Are you ready to tackle the IRS Form 1023 paperwork?"',
'    ];',
'',
'    function answerQuestion(points) {',
'      currentScore += points;',
'      currentQuestion++;',
'      if (currentQuestion <= 5) {',
'        document.getElementById("question-text").innerText = "Question " + currentQuestion + ": " + questions[currentQuestion - 1];',
'      } else {',
'        document.getElementById("quiz-content").innerHTML = `',
'          <h2 style="color: #1e293b; margin-top: 0;">🎉 Quiz Complete!</h2>',
'          <p style="color: #64748b; font-size: 14px; line-height:1.5;">Enter your primary email address below to see your custom calculation score and instantly receive your free <b>\"What Not to Paste Into AI\"</b> Safety Guide PDF.</p>',
'          <input type="email" id="user-email" placeholder="Enter your email address" required style="width: 85%; padding: 12px; margin-top: 10px; margin-bottom: 15px; border: 1px solid #cbd5e1; border-radius: 6px; font-size: 15px; outline: none;">',
'          <br>',
'          <button onclick="submitQuiz()" style="background-color: #16a34a; color: white; border: none; padding: 14px 0; font-size: 16px; font-weight: bold; border-radius: 6px; cursor: pointer; width: 90%;">Get My Results & Free PDF</button>',
'        `;',
'      }',
'    }',
'',
'    function submitQuiz() {',
'      const emailInput = document.getElementById("user-email").value;',
'      if(!emailInput || !emailInput.includes(\x27@\x27)) return alert("Please enter a valid email address!");',
'      document.getElementById("quiz-content").innerHTML = \x27<p style="color: #2563eb; font-weight: bold; font-size: 16px;">Calculating your configuration analytics...</p>\x27;',
'      fetch(GOOGLE_SCRIPT_URL, {',
'        method: "POST",',
'        mode: "no-cors", ',
'        headers: { "Content-Type": "application/json" },',
'        body: JSON.stringify({ email: emailInput, score: currentScore })',
'      }).then(() => {',
'        document.getElementById("quiz-content").innerHTML = `',
'          <h2 style="color: #16a34a; margin-top: 0;">🚀 Fly into Your Inbox!</h2>',
'          <p style="color: #334155; font-size: 16px; font-weight: 600;">Your data successfully saved.</p>',
'          <p style="color: #64748b; font-size: 14px; line-height: 1.5; margin-bottom: 20px;">We just triggered an automatic delivery email containing your custom score breakdown and your copy of the <b>AI Security & Privacy Toolkit</b>.</p>',
'        `;',
'      });',
'    }',
'  </script>',
'</body>',
'</html>'
)
$template = $templateLines -join "`r`n"

foreach ($state in $states) {
    $content = $template.Replace("{{STATE}}", $state.name).Replace("{{FEE}}", $state.fee).Replace("{{BOARD}}", $state.board).Replace("{{AGENCY}}", $state.agency)
    $filePath = Join-Path $targetFolder $state.file
    Set-Content -Path $filePath -Value $content -Encoding utf8
    Write-Host "Generated: $($state.file)"
}
Write-Host "Done! All 50 states are inside your 'nonprofit-pages' folder."